"""add llm_profiles table

Revision ID: 4add01fdf067
Revises: ce62b01d98e1
Create Date: 2026-09-27 21:10:56.101890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4add01fdf067'
down_revision = 'ce62b01d98e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('credentials_encrypted', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_profiles_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_profiles_user_id'))

    op.drop_table('llm_profiles')
    # ### end Alembic commands ###
