"""add servicenow_profiles table

Revision ID: ce62b01d98e1
Revises: c548e2ba29ea
Create Date: 2026-09-27 14:06:37.035380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce62b01d98e1'
down_revision = 'c548e2ba29ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servicenow_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('instance_url', sa.String(length=255), nullable=False),
    sa.Column('auth_type', sa.String(length=20), nullable=False),
    sa.Column('credentials_encrypted', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('servicenow_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_servicenow_profiles_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicenow_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_servicenow_profiles_user_id'))

    op.drop_table('servicenow_profiles')
    # ### end Alembic commands ###
